name: WASM Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.11.1"
          host: all_os
          target: wasm
          arch: wasm_multithread
          modules: 'qtshadertools qtgraphs qtquick3d'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build brotli

      - name: Install Emscripten
        uses: emscripten-core/setup-emsdk@v15
        with:
          version: "4.0.7"
          actions-cache-folder: 'emsdk-cache'

      - name: Configure
        run: |
          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE="$QT_ROOT_DIR/lib/cmake/Qt6/qt.toolchain.cmake"

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Compress wasm
        working-directory: build
        run: |
          brotli --best *.wasm
          for f in *.wasm.br; do
              mv "$f" "${f%.br}"
          done

      - name: Stage files
        run: |
            mkdir -p deploy
            cp build/appgraphical.html deploy/
            cp build/qtloader.js deploy/
            cp build/appgraphical.js deploy/
            cp build/appgraphical.wasm deploy/
            cat > deploy/_headers << 'EOF'
            /appgraphical.wasm
            Content-Type: application/wasm
            Content-Encoding: br
            Cross-Origin-Opener-Policy: same-origin
            Cross-Origin-Embedder-Policy: require-corp

            /*
            cross-origin-opener-policy: same-origin
            cross-origin-embedder-policy: require-corp
            EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: deploy/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOEKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: appgraphical
          directory: deploy
