name: WASM Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.0"
          host: all_os
          target: wasm
          arch: wasm_singlethread
          cache: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build brotli
      - name: Configure
        run: |
          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE="$QT_ROOT_DIR/lib/cmake/qt.toolchain.cmake"

      - name: Build
        run: |
          cmake --build build --parallel
      - name: Compress wasm
        working-directory: build
        run: |
          brotli --best *.wasm
          for f in *.wasm.br; do
              mv "$f" "${f%.br}"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: build/
